Strong types for ServiceAddress
Michael-F-Bryan/libsignal-service-rs pull request #50
Opened 2020-11-15 17:49 UTC by rubdos

- [ ] Rename `e164` fields to `phonenumber`?

Fixes #47

2020-11-16 08:51 UTC, gferon reviewed
Great! Tests of `SealedSessionCipher` are failing to compile now, I'll approve once they're fixed :smile:

2020-11-16 08:51 UTC, gferon commented on libsignal-service/src/sealed_session_cipher.rs
> +    InvalidE164Error(#[from] uuid::Error),
Maybe `InvalidPhoneNumber` and `"Supplied phone number could not be parsed in E164 format"`?

2020-11-16 08:52 UTC, gferon commented
>     * [ ]  Rename `e164` fields to `phonenumber`?

I would also agree, except it'll be difficult to use for us the first few weeks because of :muscle: memory :smile:

2020-11-30 09:11 UTC, gferon requested changes
One minor comment + one new clippy warning where we clone a `Uuid` which is a copy type (I can't comment on non PR code somehow...) + tests still fail to compile, but I'd approve this when it builds :+1:

2020-11-30 09:11 UTC, gferon commented on libsignal-service/src/receiver.rs
> +    #[error("Envelop parse error")]
```suggestion
    #[error("Envelope parsing error")]
```

2020-12-02 13:22 UTC, rubdos commented
> One minor comment + one new clippy warning where we clone a `Uuid` which is a copy type (I can't comment on non PR code somehow...) + tests still fail to compile, but I'd approve this when it builds +1

Ah, was just keeping it in sync with master for now. I can put it as draft while I'm writing whisperfish against this branch, if that's clearer.

2021-02-25 21:04 UTC, gferon commented on libsignal-service/src/receiver.rs
> +            .collect::<Result<_, _>>()?;
[gool old turbo fish](https://turbo.fish/)

2021-02-25 21:06 UTC, gferon approved these changes
LGTM! I didn't see anything suspicious, so I'd say... 🚀

2021-02-25 22:07 UTC, merged